require('dotenv').config();
const express=require('express');
const session=require('express-session');
const {router:authRouter,requireAuth}=require('./routes/auth');
const chatRoutes=require('./routes/chat');
const app=express();
app.set('trust proxy',1);
app.use(express.json());
app.use(session({secret:process.env.SESSION_SECRET||'finny',resave:false,saveUninitialized:false,cookie:{secure:false}}));
app.use('/auth',authRouter);
app.use('/chat',requireAuth,chatRoutes);
const PORT=process.env.PORT||3000;
app.listen(PORT,()=>console.log(`Finny 4.5.1 live on :${PORT}`));